/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DAO.CidadesDAO;
import DAO.ClientesDAO;
import DAO.DAO;
import control.CategoriasControl;
import control.ClientesControl;
import control.DesenvolvedoresControl;
import control.DesenvolvedoresControl;
import control.ProjetosControl;
import control.SelecionarControl;
import gerenciadorprojetos.Gerenciadorprojetos;
import java.beans.PropertyVetoException;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.spi.DirStateFactory;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import util.Funcoes;

/**
 *
 * @author Elias Müller
 * @version 0.1
 * @since 2013
 * @see lol
 *
 */
public class fPrincipal extends javax.swing.JFrame {

    char operante;
    Funcoes f = new Funcoes();
    SelecionarControl cS;
    CategoriasControl cCat;
    DesenvolvedoresControl cDes;
    ClientesControl cCli;
    ProjetosControl cPro;
    String janela;

    /**
     * Creates new form fPrincipal
     */
    public fPrincipal() {
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
            //UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            SwingUtilities.updateComponentTreeUI(this);
        } catch (Exception e) {
        }
        initComponents();

        //dpDesktop.setSize(Gerenciadorprojetos.DIMENSAO);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlSelecionar = new javax.swing.JDialog();
        lbFiltroSel1 = new javax.swing.JLabel();
        tfFiltroSel1 = new javax.swing.JTextField();
        spSelecionar1 = new javax.swing.JScrollPane();
        tbSelecionar1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        dpDesktop = new javax.swing.JDesktopPane();
        ifDesenvolvedores = new javax.swing.JInternalFrame();
        tpDesenvolvedores = new javax.swing.JTabbedPane();
        pPesquisaDes = new javax.swing.JPanel();
        lbFiltro1 = new javax.swing.JLabel();
        tfFiltroDes = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbCategorias1 = new javax.swing.JTable();
        pCadastrarDes = new javax.swing.JPanel();
        lbNomeDes = new javax.swing.JLabel();
        lbCategoriaDes = new javax.swing.JLabel();
        tfNomeDes = new javax.swing.JTextField();
        lbCodigoDes = new javax.swing.JLabel();
        cbCategoriaDes = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        ftfTelefone = new javax.swing.JFormattedTextField();
        btSalvarDes = new javax.swing.JButton();
        btSairDes = new javax.swing.JButton();
        ifCategorias = new javax.swing.JInternalFrame();
        tpCategorias = new javax.swing.JTabbedPane();
        pPesquisa = new javax.swing.JPanel();
        lbFiltro = new javax.swing.JLabel();
        tfFiltro = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCategorias = new javax.swing.JTable();
        pCadastrar = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        lbDescricao = new javax.swing.JLabel();
        tfTitulo = new javax.swing.JTextField();
        spDescricao = new javax.swing.JScrollPane();
        taDescricao = new javax.swing.JTextArea();
        lbCodigoCategoria = new javax.swing.JLabel();
        btSalvar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        ifProjetos = new javax.swing.JInternalFrame();
        tpProjetos = new javax.swing.JTabbedPane();
        pPesquisaPro = new javax.swing.JPanel();
        lbFiltroPro = new javax.swing.JLabel();
        tfFiltroPro = new javax.swing.JTextField();
        spProjetos = new javax.swing.JScrollPane();
        tbProjetos = new javax.swing.JTable();
        pCadastrarPro = new javax.swing.JPanel();
        lbTituloPro = new javax.swing.JLabel();
        lbDesenvolvedor = new javax.swing.JLabel();
        tfTituloPro = new javax.swing.JTextField();
        lbCodigoPro = new javax.swing.JLabel();
        spDesenvolvedoresPro = new javax.swing.JScrollPane();
        tbDesenvolvedoresPro = new javax.swing.JTable();
        tfClientePro = new javax.swing.JTextField();
        lbClientePro = new javax.swing.JLabel();
        btAdicionarDesenvolvedorPro = new javax.swing.JButton();
        btBuscarClientePro = new javax.swing.JButton();
        btCadastrarClientePro = new javax.swing.JButton();
        lbDataPrevisao = new javax.swing.JLabel();
        lbDatainicio = new javax.swing.JLabel();
        ftfDataInicioPro = new javax.swing.JFormattedTextField();
        ftfDataPrevisaoPro = new javax.swing.JFormattedTextField();
        chProjetoPro = new javax.swing.JCheckBox();
        lbDescricaoPro = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        taDescricaoProjeto = new javax.swing.JTextArea();
        tpTopicos = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        spTopicosPro = new javax.swing.JScrollPane();
        tbTopicosPro = new javax.swing.JTable();
        spDescricaoTopicoPro = new javax.swing.JScrollPane();
        taDescricaoTopicoPro = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        lbTopicos = new javax.swing.JLabel();
        btSalvarTopicoPro = new javax.swing.JButton();
        btSalvarPro = new javax.swing.JButton();
        btSairPro = new javax.swing.JButton();
        ifClientes = new javax.swing.JInternalFrame();
        tpClientes = new javax.swing.JTabbedPane();
        pPesquisaCli = new javax.swing.JPanel();
        lbFiltroCli = new javax.swing.JLabel();
        tfFiltroCli = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pCadastrarCli = new javax.swing.JPanel();
        lbNomeCli = new javax.swing.JLabel();
        tfNomeCli = new javax.swing.JTextField();
        lbCodigoCli = new javax.swing.JLabel();
        lbTelefoneCli = new javax.swing.JLabel();
        lbEmailCli = new javax.swing.JLabel();
        tfEmailCli = new javax.swing.JTextField();
        ftfTelefoneCli = new javax.swing.JFormattedTextField();
        lbCidadeCli = new javax.swing.JLabel();
        tfCidadeCli = new javax.swing.JTextField();
        pCidadesCli = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        taAdicionalCli = new javax.swing.JTextArea();
        btSalvarCli = new javax.swing.JButton();
        btSairCli = new javax.swing.JButton();
        mbMenuTotal = new javax.swing.JMenuBar();
        mArquivo = new javax.swing.JMenu();
        mDesenvolvedores = new javax.swing.JMenu();
        miCadDesenvolvedores = new javax.swing.JMenuItem();
        miCadCategorias = new javax.swing.JMenuItem();
        mClientes = new javax.swing.JMenuItem();
        mProjetos = new javax.swing.JMenu();
        jmProjetos = new javax.swing.JMenuItem();
        jmTopicos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        dlSelecionar.setModal(true);

        lbFiltroSel1.setText("Filtro:");

        tfFiltroSel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfFiltroSel1KeyReleased(evt);
            }
        });

        tbSelecionar1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbSelecionar1.setToolTipText("");
        spSelecionar1.setViewportView(tbSelecionar1);

        javax.swing.GroupLayout dlSelecionarLayout = new javax.swing.GroupLayout(dlSelecionar.getContentPane());
        dlSelecionar.getContentPane().setLayout(dlSelecionarLayout);
        dlSelecionarLayout.setHorizontalGroup(
            dlSelecionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlSelecionarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dlSelecionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spSelecionar1)
                    .addGroup(dlSelecionarLayout.createSequentialGroup()
                        .addComponent(lbFiltroSel1)
                        .addGap(19, 19, 19)
                        .addComponent(tfFiltroSel1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 11, Short.MAX_VALUE)))
                .addContainerGap())
        );
        dlSelecionarLayout.setVerticalGroup(
            dlSelecionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlSelecionarLayout.createSequentialGroup()
                .addGroup(dlSelecionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfFiltroSel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbFiltroSel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spSelecionar1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel10.setText("jLabel10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciador de Projetos");

        dpDesktop.setMinimumSize(new java.awt.Dimension(600, 400));

        ifDesenvolvedores.setTitle("Desenvolvedores");
        ifDesenvolvedores.setVisible(false);

        tpDesenvolvedores.setEnabled(false);

        lbFiltro1.setText("Filtro:");

        tfFiltroDes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfFiltroDesKeyReleased(evt);
            }
        });

        tbCategorias1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbCategorias1.setToolTipText("");
        jScrollPane2.setViewportView(tbCategorias1);

        javax.swing.GroupLayout pPesquisaDesLayout = new javax.swing.GroupLayout(pPesquisaDes);
        pPesquisaDes.setLayout(pPesquisaDesLayout);
        pPesquisaDesLayout.setHorizontalGroup(
            pPesquisaDesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPesquisaDesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pPesquisaDesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                    .addGroup(pPesquisaDesLayout.createSequentialGroup()
                        .addComponent(lbFiltro1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfFiltroDes)))
                .addContainerGap())
        );
        pPesquisaDesLayout.setVerticalGroup(
            pPesquisaDesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPesquisaDesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pPesquisaDesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfFiltroDes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbFiltro1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        tpDesenvolvedores.addTab("Pesquisar", pPesquisaDes);

        lbNomeDes.setText("* Nome:");

        lbCategoriaDes.setText("* Categoria:");

        lbCodigoDes.setText("1");

        jLabel1.setText("Telefone:");

        jLabel2.setText("Email:");

        ftfTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("(##)-####-####"))));

        javax.swing.GroupLayout pCadastrarDesLayout = new javax.swing.GroupLayout(pCadastrarDes);
        pCadastrarDes.setLayout(pCadastrarDesLayout);
        pCadastrarDesLayout.setHorizontalGroup(
            pCadastrarDesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCadastrarDesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pCadastrarDesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfNomeDes)
                    .addGroup(pCadastrarDesLayout.createSequentialGroup()
                        .addComponent(lbNomeDes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 550, Short.MAX_VALUE)
                        .addComponent(lbCodigoDes))
                    .addComponent(tfEmail)
                    .addComponent(cbCategoriaDes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pCadastrarDesLayout.createSequentialGroup()
                        .addGroup(pCadastrarDesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(lbCategoriaDes))
                        .addGap(0, 380, Short.MAX_VALUE))
                    .addComponent(ftfTelefone))
                .addContainerGap())
        );
        pCadastrarDesLayout.setVerticalGroup(
            pCadastrarDesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCadastrarDesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pCadastrarDesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNomeDes)
                    .addComponent(lbCodigoDes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNomeDes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ftfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbCategoriaDes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbCategoriaDes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        tpDesenvolvedores.addTab("Manutenção", pCadastrarDes);

        btSalvarDes.setText("Novo");
        btSalvarDes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarDesActionPerformed(evt);
            }
        });

        btSairDes.setText("Saír");
        btSairDes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairDesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ifDesenvolvedoresLayout = new javax.swing.GroupLayout(ifDesenvolvedores.getContentPane());
        ifDesenvolvedores.getContentPane().setLayout(ifDesenvolvedoresLayout);
        ifDesenvolvedoresLayout.setHorizontalGroup(
            ifDesenvolvedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ifDesenvolvedoresLayout.createSequentialGroup()
                .addComponent(btSalvarDes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSairDes))
            .addComponent(tpDesenvolvedores, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
        );
        ifDesenvolvedoresLayout.setVerticalGroup(
            ifDesenvolvedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ifDesenvolvedoresLayout.createSequentialGroup()
                .addGroup(ifDesenvolvedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSairDes)
                    .addComponent(btSalvarDes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tpDesenvolvedores))
        );

        ifDesenvolvedores.setBounds(270, 60, 510, 410);
        dpDesktop.add(ifDesenvolvedores, javax.swing.JLayeredPane.DEFAULT_LAYER);

        ifCategorias.setBorder(null);
        ifCategorias.setTitle("Categorias de Desenvolvedores");
        ifCategorias.setComponentPopupMenu(null);
        ifCategorias.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ifCategorias.setVisible(false);

        tpCategorias.setEnabled(false);

        lbFiltro.setText("Filtro:");

        tfFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfFiltroKeyReleased(evt);
            }
        });

        tbCategorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbCategorias);

        javax.swing.GroupLayout pPesquisaLayout = new javax.swing.GroupLayout(pPesquisa);
        pPesquisa.setLayout(pPesquisaLayout);
        pPesquisaLayout.setHorizontalGroup(
            pPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                    .addGroup(pPesquisaLayout.createSequentialGroup()
                        .addComponent(lbFiltro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfFiltro)))
                .addContainerGap())
        );
        pPesquisaLayout.setVerticalGroup(
            pPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbFiltro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        tpCategorias.addTab("Pesquisar", pPesquisa);

        lbTitulo.setText("Título");

        lbDescricao.setText("Descrição:");

        taDescricao.setColumns(20);
        taDescricao.setRows(5);
        spDescricao.setViewportView(taDescricao);

        lbCodigoCategoria.setText("1");

        javax.swing.GroupLayout pCadastrarLayout = new javax.swing.GroupLayout(pCadastrar);
        pCadastrar.setLayout(pCadastrarLayout);
        pCadastrarLayout.setHorizontalGroup(
            pCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pCadastrarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(spDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                    .addComponent(tfTitulo, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pCadastrarLayout.createSequentialGroup()
                        .addComponent(lbDescricao)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pCadastrarLayout.createSequentialGroup()
                        .addComponent(lbTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbCodigoCategoria)))
                .addContainerGap())
        );
        pCadastrarLayout.setVerticalGroup(
            pCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCadastrarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTitulo)
                    .addComponent(lbCodigoCategoria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbDescricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                .addContainerGap())
        );

        tpCategorias.addTab("Manutenção", pCadastrar);

        btSalvar.setText("Novo");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btSair.setText("Saír");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ifCategoriasLayout = new javax.swing.GroupLayout(ifCategorias.getContentPane());
        ifCategorias.getContentPane().setLayout(ifCategoriasLayout);
        ifCategoriasLayout.setHorizontalGroup(
            ifCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ifCategoriasLayout.createSequentialGroup()
                .addComponent(btSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSair))
            .addComponent(tpCategorias)
        );
        ifCategoriasLayout.setVerticalGroup(
            ifCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ifCategoriasLayout.createSequentialGroup()
                .addGroup(ifCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvar)
                    .addComponent(btSair))
                .addGap(4, 4, 4)
                .addComponent(tpCategorias))
        );

        ifCategorias.setBounds(270, 60, 510, 410);
        dpDesktop.add(ifCategorias, javax.swing.JLayeredPane.PALETTE_LAYER);

        ifProjetos.setTitle("Projetos");
        ifProjetos.setVisible(false);

        tpProjetos.setEnabled(false);

        lbFiltroPro.setText("Filtro:");

        tfFiltroPro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfFiltroProKeyReleased(evt);
            }
        });

        tbProjetos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbProjetos.setToolTipText("");
        spProjetos.setViewportView(tbProjetos);

        javax.swing.GroupLayout pPesquisaProLayout = new javax.swing.GroupLayout(pPesquisaPro);
        pPesquisaPro.setLayout(pPesquisaProLayout);
        pPesquisaProLayout.setHorizontalGroup(
            pPesquisaProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPesquisaProLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pPesquisaProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spProjetos, javax.swing.GroupLayout.DEFAULT_SIZE, 933, Short.MAX_VALUE)
                    .addGroup(pPesquisaProLayout.createSequentialGroup()
                        .addComponent(lbFiltroPro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfFiltroPro)))
                .addContainerGap())
        );
        pPesquisaProLayout.setVerticalGroup(
            pPesquisaProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPesquisaProLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pPesquisaProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfFiltroPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbFiltroPro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spProjetos, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE))
        );

        tpProjetos.addTab("Pesquisar", pPesquisaPro);

        lbTituloPro.setText("* Título:");

        lbDesenvolvedor.setText("*Desenvolvedores:");

        lbCodigoPro.setForeground(new java.awt.Color(250, 250, 250));
        lbCodigoPro.setText("1");

        tbDesenvolvedoresPro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        spDesenvolvedoresPro.setViewportView(tbDesenvolvedoresPro);

        tfClientePro.setEditable(false);
        tfClientePro.setToolTipText("Preencimento somente via botão Buscar.");

        lbClientePro.setText("Cliente:");

        btAdicionarDesenvolvedorPro.setText("Adicionar");

        btBuscarClientePro.setText("Buscar");
        btBuscarClientePro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarClienteProActionPerformed(evt);
            }
        });

        btCadastrarClientePro.setText("Cadastrar");

        lbDataPrevisao.setText("Data de Previsão:");

        lbDatainicio.setText("Data de Início:");

        ftfDataInicioPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftfDataInicioProActionPerformed(evt);
            }
        });

        chProjetoPro.setText("Pronto");

        lbDescricaoPro.setText("Descricao:");

        taDescricaoProjeto.setColumns(20);
        taDescricaoProjeto.setRows(5);
        jScrollPane3.setViewportView(taDescricaoProjeto);

        tpTopicos.setEnabled(false);

        tbTopicosPro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbTopicosPro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        spTopicosPro.setViewportView(tbTopicosPro);

        taDescricaoTopicoPro.setColumns(20);
        taDescricaoTopicoPro.setRows(5);
        spDescricaoTopicoPro.setViewportView(taDescricaoTopicoPro);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addComponent(spTopicosPro, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spDescricaoTopicoPro, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spDescricaoTopicoPro, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spTopicosPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(131, Short.MAX_VALUE))
        );

        tpTopicos.addTab("Topicos do Projeto", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 516, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 571, Short.MAX_VALUE)
        );

        tpTopicos.addTab("Manutenção", jPanel2);

        lbTopicos.setText("Tópicos:");

        btSalvarTopicoPro.setText("Novo");

        javax.swing.GroupLayout pCadastrarProLayout = new javax.swing.GroupLayout(pCadastrarPro);
        pCadastrarPro.setLayout(pCadastrarProLayout);
        pCadastrarProLayout.setHorizontalGroup(
            pCadastrarProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCadastrarProLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pCadastrarProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pCadastrarProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(pCadastrarProLayout.createSequentialGroup()
                            .addComponent(tfTituloPro, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(chProjetoPro, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addComponent(lbClientePro)
                        .addComponent(ftfDataInicioPro, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ftfDataPrevisaoPro, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbDataPrevisao)
                        .addGroup(pCadastrarProLayout.createSequentialGroup()
                            .addComponent(lbDesenvolvedor)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btAdicionarDesenvolvedorPro))
                        .addComponent(lbDatainicio)
                        .addGroup(pCadastrarProLayout.createSequentialGroup()
                            .addComponent(tfClientePro, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btBuscarClientePro)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btCadastrarClientePro))
                        .addComponent(lbDescricaoPro)
                        .addComponent(jScrollPane3)
                        .addComponent(spDesenvolvedoresPro, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(lbTituloPro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pCadastrarProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pCadastrarProLayout.createSequentialGroup()
                        .addComponent(lbTopicos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btSalvarTopicoPro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbCodigoPro))
                    .addGroup(pCadastrarProLayout.createSequentialGroup()
                        .addComponent(tpTopicos)
                        .addContainerGap())))
        );
        pCadastrarProLayout.setVerticalGroup(
            pCadastrarProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCadastrarProLayout.createSequentialGroup()
                .addGroup(pCadastrarProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pCadastrarProLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pCadastrarProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTituloPro)
                            .addComponent(lbTopicos)
                            .addComponent(btSalvarTopicoPro)))
                    .addComponent(lbCodigoPro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pCadastrarProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pCadastrarProLayout.createSequentialGroup()
                        .addGroup(pCadastrarProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfTituloPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chProjetoPro))
                        .addGap(8, 8, 8)
                        .addComponent(lbDescricaoPro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbClientePro)
                        .addGap(1, 1, 1)
                        .addGroup(pCadastrarProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfClientePro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btBuscarClientePro)
                            .addComponent(btCadastrarClientePro))
                        .addGap(5, 5, 5)
                        .addComponent(lbDatainicio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ftfDataInicioPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbDataPrevisao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ftfDataPrevisaoPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pCadastrarProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbDesenvolvedor)
                            .addComponent(btAdicionarDesenvolvedorPro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spDesenvolvedoresPro, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(tpTopicos)))
        );

        tpProjetos.addTab("Manutenção", pCadastrarPro);

        btSalvarPro.setText("Novo");
        btSalvarPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarProActionPerformed(evt);
            }
        });

        btSairPro.setText("Saír");
        btSairPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairProActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ifProjetosLayout = new javax.swing.GroupLayout(ifProjetos.getContentPane());
        ifProjetos.getContentPane().setLayout(ifProjetosLayout);
        ifProjetosLayout.setHorizontalGroup(
            ifProjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ifProjetosLayout.createSequentialGroup()
                .addComponent(btSalvarPro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSairPro))
            .addComponent(tpProjetos)
        );
        ifProjetosLayout.setVerticalGroup(
            ifProjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ifProjetosLayout.createSequentialGroup()
                .addGroup(ifProjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvarPro)
                    .addComponent(btSairPro))
                .addGap(18, 18, 18)
                .addComponent(tpProjetos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        ifProjetos.setBounds(270, 60, 510, 410);
        dpDesktop.add(ifProjetos, javax.swing.JLayeredPane.DEFAULT_LAYER);

        ifClientes.setTitle("Clientes");
        ifClientes.setVisible(false);

        tpClientes.setEnabled(false);

        lbFiltroCli.setText("Filtro:");

        tfFiltroCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfFiltroCliKeyReleased(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable1);

        javax.swing.GroupLayout pPesquisaCliLayout = new javax.swing.GroupLayout(pPesquisaCli);
        pPesquisaCli.setLayout(pPesquisaCliLayout);
        pPesquisaCliLayout.setHorizontalGroup(
            pPesquisaCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPesquisaCliLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pPesquisaCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                    .addGroup(pPesquisaCliLayout.createSequentialGroup()
                        .addComponent(lbFiltroCli)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfFiltroCli, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pPesquisaCliLayout.setVerticalGroup(
            pPesquisaCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPesquisaCliLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pPesquisaCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfFiltroCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbFiltroCli))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        tpClientes.addTab("Pesquisar", pPesquisaCli);

        lbNomeCli.setForeground(new java.awt.Color(169, 53, 53));
        lbNomeCli.setText(" Nome:");

        lbCodigoCli.setText("1");

        lbTelefoneCli.setText("Telefone:");

        lbEmailCli.setText("Email:");

        lbCidadeCli.setForeground(new java.awt.Color(169, 53, 53));
        lbCidadeCli.setText(" Cidade:");

        tfCidadeCli.setEditable(false);

        javax.swing.GroupLayout pCidadesCliLayout = new javax.swing.GroupLayout(pCidadesCli);
        pCidadesCli.setLayout(pCidadesCliLayout);
        pCidadesCliLayout.setHorizontalGroup(
            pCidadesCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pCidadesCliLayout.setVerticalGroup(
            pCidadesCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pesquisar.png"))); // NOI18N
        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Observação: Campos em vermelho são obrigatórios!");

        jLabel6.setText("Dados Adicionais:");

        taAdicionalCli.setColumns(20);
        taAdicionalCli.setRows(5);
        jScrollPane5.setViewportView(taAdicionalCli);

        javax.swing.GroupLayout pCadastrarCliLayout = new javax.swing.GroupLayout(pCadastrarCli);
        pCadastrarCli.setLayout(pCadastrarCliLayout);
        pCadastrarCliLayout.setHorizontalGroup(
            pCadastrarCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCadastrarCliLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pCadastrarCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addGroup(pCadastrarCliLayout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(pCidadesCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(tfNomeCli)
                    .addGroup(pCadastrarCliLayout.createSequentialGroup()
                        .addComponent(lbNomeCli)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbCodigoCli))
                    .addComponent(tfEmailCli)
                    .addComponent(ftfTelefoneCli)
                    .addGroup(pCadastrarCliLayout.createSequentialGroup()
                        .addGroup(pCadastrarCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbCidadeCli)
                            .addComponent(lbTelefoneCli)
                            .addComponent(lbEmailCli)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pCadastrarCliLayout.createSequentialGroup()
                        .addComponent(tfCidadeCli, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        pCadastrarCliLayout.setVerticalGroup(
            pCadastrarCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCadastrarCliLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pCadastrarCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNomeCli)
                    .addComponent(lbCodigoCli))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNomeCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTelefoneCli)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ftfTelefoneCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbEmailCli)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfEmailCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbCidadeCli)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pCadastrarCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfCidadeCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(64, 64, 64)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(24, 24, 24)
                .addComponent(pCidadesCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tpClientes.addTab("Manutenção", pCadastrarCli);

        btSalvarCli.setText("Novo");
        btSalvarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarCliActionPerformed(evt);
            }
        });

        btSairCli.setText("Saír");
        btSairCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairCliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ifClientesLayout = new javax.swing.GroupLayout(ifClientes.getContentPane());
        ifClientes.getContentPane().setLayout(ifClientesLayout);
        ifClientesLayout.setHorizontalGroup(
            ifClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ifClientesLayout.createSequentialGroup()
                .addComponent(btSalvarCli)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSairCli))
            .addComponent(tpClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
        );
        ifClientesLayout.setVerticalGroup(
            ifClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ifClientesLayout.createSequentialGroup()
                .addGroup(ifClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSairCli)
                    .addComponent(btSalvarCli))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tpClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE))
        );

        ifClientes.setBounds(270, 60, 510, 410);
        dpDesktop.add(ifClientes, javax.swing.JLayeredPane.DEFAULT_LAYER);

        mArquivo.setText("Arquivo");

        mDesenvolvedores.setText("Desenvolvedores");

        miCadDesenvolvedores.setText("Cadastro de Desenvolvedores");
        miCadDesenvolvedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadDesenvolvedoresActionPerformed(evt);
            }
        });
        mDesenvolvedores.add(miCadDesenvolvedores);

        miCadCategorias.setText("Cadastro de Categorias");
        miCadCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadCategoriasActionPerformed(evt);
            }
        });
        mDesenvolvedores.add(miCadCategorias);

        mArquivo.add(mDesenvolvedores);

        mClientes.setText("Clientes");
        mClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mClientesActionPerformed(evt);
            }
        });
        mArquivo.add(mClientes);

        mProjetos.setText("Projetos");

        jmProjetos.setText("Cadastro de Projetos");
        jmProjetos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmProjetosActionPerformed(evt);
            }
        });
        mProjetos.add(jmProjetos);

        jmTopicos.setText("Cadastro de topicos");
        mProjetos.add(jmTopicos);

        mArquivo.add(mProjetos);

        mbMenuTotal.add(mArquivo);

        jMenu2.setText("Edit");
        mbMenuTotal.add(jMenu2);

        setJMenuBar(mbMenuTotal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpDesktop, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpDesktop, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miCadDesenvolvedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadDesenvolvedoresActionPerformed
        cDes = new DesenvolvedoresControl(null, tpDesenvolvedores, cbCategoriaDes, tfNomeDes, ftfTelefone, tfEmail, pPesquisaDes, pCadastrarDes, ifDesenvolvedores,
                btSalvarDes, tfFiltroDes, tbCategorias1, lbCodigoDes, ifDesenvolvedores);
        cDes.pupulaComboCategorias();
        cDes.populaDesenvolvedores();
        ifDesenvolvedores.setVisible(true);
    }//GEN-LAST:event_miCadDesenvolvedoresActionPerformed

    private void miCadCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadCategoriasActionPerformed
        cCat = new CategoriasControl();
        cCat.populaCategorias(tfFiltro, tbCategorias, tpCategorias, btSalvar, tfTitulo, taDescricao, lbCodigoCategoria);
        ifCategorias.setVisible(true);
    }//GEN-LAST:event_miCadCategoriasActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        cCat.acaoBotaoNovoSalvar(tpCategorias, tfTitulo, pCadastrar, taDescricao, ifCategorias, btSalvar, tfFiltro, tbCategorias, lbCodigoCategoria);
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        cCat.acaoSair(ifCategorias, tpCategorias, pCadastrar, pPesquisa, btSalvar);
        taDescricao.setText("");
        cCat = null;
    }//GEN-LAST:event_btSairActionPerformed

    private void tfFiltroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfFiltroKeyReleased
        cCat.populaCategorias(tfFiltro, tbCategorias, tpCategorias, btSalvar, tfTitulo, taDescricao, lbCodigoCategoria);
    }//GEN-LAST:event_tfFiltroKeyReleased

    private void tfFiltroDesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfFiltroDesKeyReleased
        cDes.populaDesenvolvedores();
    }//GEN-LAST:event_tfFiltroDesKeyReleased

    private void btSalvarDesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarDesActionPerformed
        cDes.acaoBotaoNovoSalvar();
    }//GEN-LAST:event_btSalvarDesActionPerformed

    private void btSairDesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairDesActionPerformed
        cDes.acaoSair();
        cDes = null;
    }//GEN-LAST:event_btSairDesActionPerformed

    private void tfFiltroProKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfFiltroProKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tfFiltroProKeyReleased

    private void btSalvarProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarProActionPerformed
        cPro.acaoBotaoNovoSalvar();
        // TODO add your handling code here:
    }//GEN-LAST:event_btSalvarProActionPerformed

    private void btSairProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairProActionPerformed
        cPro.acaoSair();
        cPro = null;
    }//GEN-LAST:event_btSairProActionPerformed

    private void tfFiltroCliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfFiltroCliKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tfFiltroCliKeyReleased

    private void btSalvarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarCliActionPerformed
        cCli.acaoBotaoNovoSalvar();
    }//GEN-LAST:event_btSalvarCliActionPerformed

    private void btSairCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairCliActionPerformed
        cCli.acaoBotaoSair();
    }//GEN-LAST:event_btSairCliActionPerformed

    private void mClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mClientesActionPerformed
        cCli = new ClientesControl(jTable1);
        cCli.setTb(jTable1);
        cCli.setBtSalvar(btSalvarCli);
        cCli.setBtSair(btSairCli);
        cCli.setAdicional(taAdicionalCli);
        cCli.setCodigo(lbCodigoCli);
        cCli.setEmail(tfEmailCli);
        cCli.setFrame(ifClientes);
        cCli.setFiltro(tfFiltroCli);
        cCli.setNome(tfNomeCli);
        cCli.setTelefone(ftfTelefoneCli);
        cCli.setTp(tpClientes);
        cCli.setCidade(tfCidadeCli);
        cCli.setP(pPesquisaCli);
        cCli.setP2(pCadastrarCli);
//        Funcoes.populaTabela(jTable1, "idcidade,Nome,Telefone,Email,Cidade", new ClientesDAO().resultado(tfFiltroCli.getText()), "idcidade,nome,telefone,email,cidade");
        ifClientes.setVisible(true);
    }//GEN-LAST:event_mClientesActionPerformed

    private void tfFiltroSel1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfFiltroSel1KeyReleased
        cS.filtro();
    }//GEN-LAST:event_tfFiltroSel1KeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        cS = new SelecionarControl();
        cS.setDl(dlSelecionar);
        cS.setJanela("cidades");
        cS.setFiltro(tfFiltroSel1);
        cS.setTb(tbSelecionar1);
        cS.filtro();
        if(cS.getCodigo()!=null){
        cCli.setIdcidade(cS.getCodigo());
        }
        tfCidadeCli.setText(new CidadesDAO().linha(cCli.getIdcidade()).getNome());

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jmProjetosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmProjetosActionPerformed

        cPro = new ProjetosControl();
        cPro.setForm(ifProjetos);
        cPro.setTp(tpProjetos);
        cPro.setP1(pPesquisaPro);
        cPro.setP2(pCadastrarPro);
        cPro.setBt(btSalvarPro);
        cPro.setTb(tbProjetos);

        cPro.setBtSalvar(btSalvarPro);
        cPro.setCliente(tfClientePro);
        cPro.setTitulo(tfTituloPro);
        cPro.setDescricao(taDescricaoProjeto);
        cPro.setCodigo(lbCodigoPro);
        cPro.setDataInicio(ftfDataInicioPro);
        cPro.setDataPrevisao(ftfDataPrevisaoPro);
        cPro.setDesenvolvedores(tbDesenvolvedoresPro);
        cPro.setTopicos(tbTopicosPro);
        cPro.popularProjetos("");
        ifProjetos.setVisible(true);


    }//GEN-LAST:event_jmProjetosActionPerformed

    private void btBuscarClienteProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarClienteProActionPerformed
        cS = new SelecionarControl();
        cS.setDl(dlSelecionar);
        cS.setJanela("clientes");
        cS.setFiltro(tfFiltroSel1);
        cS.setTb(tbSelecionar1);
        cS.filtro();
        cPro.setIdCliente(Integer.parseInt(cS.getCodigo()));
        tfClientePro.setText(new ClientesDAO().linha(cPro.getIdCliente() + "").getNome());
    }//GEN-LAST:event_btBuscarClienteProActionPerformed

    private void ftfDataInicioProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftfDataInicioProActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftfDataInicioProActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdicionarDesenvolvedorPro;
    private javax.swing.JButton btBuscarClientePro;
    private javax.swing.JButton btCadastrarClientePro;
    private javax.swing.JButton btSair;
    private javax.swing.JButton btSairCli;
    private javax.swing.JButton btSairDes;
    private javax.swing.JButton btSairPro;
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton btSalvarCli;
    private javax.swing.JButton btSalvarDes;
    private javax.swing.JButton btSalvarPro;
    private javax.swing.JButton btSalvarTopicoPro;
    private javax.swing.JComboBox cbCategoriaDes;
    private javax.swing.JCheckBox chProjetoPro;
    private javax.swing.JDialog dlSelecionar;
    private javax.swing.JDesktopPane dpDesktop;
    private javax.swing.JFormattedTextField ftfDataInicioPro;
    private javax.swing.JFormattedTextField ftfDataPrevisaoPro;
    private javax.swing.JFormattedTextField ftfTelefone;
    private javax.swing.JFormattedTextField ftfTelefoneCli;
    private javax.swing.JInternalFrame ifCategorias;
    private javax.swing.JInternalFrame ifClientes;
    private javax.swing.JInternalFrame ifDesenvolvedores;
    private javax.swing.JInternalFrame ifProjetos;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenuItem jmProjetos;
    private javax.swing.JMenuItem jmTopicos;
    private javax.swing.JLabel lbCategoriaDes;
    private javax.swing.JLabel lbCidadeCli;
    private javax.swing.JLabel lbClientePro;
    private javax.swing.JLabel lbCodigoCategoria;
    private javax.swing.JLabel lbCodigoCli;
    private javax.swing.JLabel lbCodigoDes;
    private javax.swing.JLabel lbCodigoPro;
    private javax.swing.JLabel lbDataPrevisao;
    private javax.swing.JLabel lbDatainicio;
    private javax.swing.JLabel lbDescricao;
    private javax.swing.JLabel lbDescricaoPro;
    private javax.swing.JLabel lbDesenvolvedor;
    private javax.swing.JLabel lbEmailCli;
    private javax.swing.JLabel lbFiltro;
    private javax.swing.JLabel lbFiltro1;
    private javax.swing.JLabel lbFiltroCli;
    private javax.swing.JLabel lbFiltroPro;
    private javax.swing.JLabel lbFiltroSel1;
    private javax.swing.JLabel lbNomeCli;
    private javax.swing.JLabel lbNomeDes;
    private javax.swing.JLabel lbTelefoneCli;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JLabel lbTituloPro;
    private javax.swing.JLabel lbTopicos;
    private javax.swing.JMenu mArquivo;
    private javax.swing.JMenuItem mClientes;
    private javax.swing.JMenu mDesenvolvedores;
    private javax.swing.JMenu mProjetos;
    private javax.swing.JMenuBar mbMenuTotal;
    private javax.swing.JMenuItem miCadCategorias;
    private javax.swing.JMenuItem miCadDesenvolvedores;
    private javax.swing.JPanel pCadastrar;
    private javax.swing.JPanel pCadastrarCli;
    private javax.swing.JPanel pCadastrarDes;
    private javax.swing.JPanel pCadastrarPro;
    private javax.swing.JPanel pCidadesCli;
    private javax.swing.JPanel pPesquisa;
    private javax.swing.JPanel pPesquisaCli;
    private javax.swing.JPanel pPesquisaDes;
    private javax.swing.JPanel pPesquisaPro;
    private javax.swing.JScrollPane spDescricao;
    private javax.swing.JScrollPane spDescricaoTopicoPro;
    private javax.swing.JScrollPane spDesenvolvedoresPro;
    private javax.swing.JScrollPane spProjetos;
    private javax.swing.JScrollPane spSelecionar1;
    private javax.swing.JScrollPane spTopicosPro;
    private javax.swing.JTextArea taAdicionalCli;
    private javax.swing.JTextArea taDescricao;
    private javax.swing.JTextArea taDescricaoProjeto;
    private javax.swing.JTextArea taDescricaoTopicoPro;
    private javax.swing.JTable tbCategorias;
    private javax.swing.JTable tbCategorias1;
    private javax.swing.JTable tbDesenvolvedoresPro;
    private javax.swing.JTable tbProjetos;
    private javax.swing.JTable tbSelecionar1;
    private javax.swing.JTable tbTopicosPro;
    private javax.swing.JTextField tfCidadeCli;
    private javax.swing.JTextField tfClientePro;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfEmailCli;
    private javax.swing.JTextField tfFiltro;
    private javax.swing.JTextField tfFiltroCli;
    private javax.swing.JTextField tfFiltroDes;
    private javax.swing.JTextField tfFiltroPro;
    private javax.swing.JTextField tfFiltroSel1;
    private javax.swing.JTextField tfNomeCli;
    private javax.swing.JTextField tfNomeDes;
    private javax.swing.JTextField tfTitulo;
    private javax.swing.JTextField tfTituloPro;
    private javax.swing.JTabbedPane tpCategorias;
    private javax.swing.JTabbedPane tpClientes;
    private javax.swing.JTabbedPane tpDesenvolvedores;
    private javax.swing.JTabbedPane tpProjetos;
    private javax.swing.JTabbedPane tpTopicos;
    // End of variables declaration//GEN-END:variables
}
